### ISSUE TITLE
question: any good first issue?

### ISSUE THREAD

**Issue by uncomfyhalomacro** [rpm-rs/rpm#103]
Hello. I am planning to learn Rust (again) because my schedule now allows me to do so. Are there any `good first issue` for this project that I can contribute to and some resources about rpm? I have written lots rpm specfiles for openSUSE and I am now interested in this project for my package manager project in Rust. Sorry if I sound stupid!

**Comment by dralley** [comment]
@uncomfyhalomacro Thanks for your interest!  I will label a couple of the existing issues as good first issues

In particular I think some comparison tests for packages built with `rpm-rs` vs `rpmbuild` would be helpful but feel free to pick anything.
