### ISSUE TITLE
Package checksums are not calculated during build when "signature-meta" feature is disabled

### ISSUE THREAD

**Issue by dralley** [rpm-rs/rpm#105]
Not verifying digests during parsing is one thing, but them to not be created during package build feels like maybe a step too far?  It means there would be no internal mechanism for detecting corruption of the payload.

https://github.com/rpm-rs/rpm/blob/86b9bd13c31df0bedebd2ad190ec84d1256bf152/src/rpm/builder.rs

**Comment by dralley** [comment]
@drahnr What do you think?

**Comment by drahnr** [comment]
I agree, if signing is not enabled, the hashes should still be present, and checked if present when parsing.

**Comment by dralley** [comment]
I meant to link the specific line https://github.com/rpm-rs/rpm/blob/86b9bd13c31df0bedebd2ad190ec84d1256bf152/src/rpm/builder.rs#L410

**Comment by dralley** [comment]
Are you onboard with dropping the signature-meta feature, then?  I'm not sure if it's doing anything else
