### ISSUE TITLE
RPM Announcement and what this means to this project

### ISSUE THREAD

**Issue by uncomfyhalomacro** [rpm-rs/rpm#112]
I saw this announcement from rpm: https://github.com/rpm-software-management/rpm/discussions/2461

If this is true, what would this mean for this project?

**Comment by dralley** [comment]
It's just an April Fools joke, not a serious announcement :)

I don't forsee them utilizing more Rust in the immediate future, but of course if they do I would personally be open to collaboration.

**Comment by uncomfyhalomacro** [comment]
gotcha. forgot it's april 1 🫣
