### ISSUE TITLE
Potential validity issues with generated RPMs

### ISSUE THREAD

**Issue by newpavlov** [rpm-rs/rpm#147]
Let's take this [dummy library](https://github.com/newpavlov/libdummyadd) as an example. By running `cargo build --release` and `cargo generate-rpm` we get `libdummyadd-0.1.0-1.x86_64.rpm`. It can be installed and uninstalled without issues. But if we run `rpm --rebuilddb` after installation, we get the following warning: `error: header #2054 in the database is bad -- skipping.`. Now the packet is not listed as installed, e.g. we can no longer remove it using packet manager. Additionally, `mc` can not open generated packets, while it handles packets generated by `rpmbuild` just fine. This behavior can be reproduced on at least CentOS 7 and Fedora 32.

This can be reproduced by using the latest version of `rpm` crate directly:
<details> 
  <summary>Expand</summary>

```rust
let pkg = rpm::RPMBuilder::new(
    "libdummyadd",
    "0.1.0",
    "UNLICENSE",
    "x86_64",
    "Dummy library for testing RPM generation",
)
.compression(rpm::CompressionType::None)
.with_file(
    "/path/to/libdummyadd/target/release/libdummyadd.so",
    rpm::RPMFileOptions::new("/usr/lib64/libdummyadd.so"),
)?
.build_time(rpm::chrono::Utc::now())
.build_host("host".to_string())
.vendor("NA")
.build()?;

let mut f = std::fs::File::create("libdummyadd.rpm")?;
pkg.write(&mut f)?;
```

</details>

If my understanding is correct, the headers added after installation of the package are considered invalid by RPM, meaning that RPMs generated by this crate may not be completely valid.

**Comment by dralley** [comment]
What happens with `--verifydb`?

**Comment by dralley** [comment]
The problem *might* be that RPM wants the buildtime to be set.  Could you try setting the build time, rebuilding and reinstalling the package?

https://github.com/rpm-software-management/rpm/blob/83413bfd3949d7a1f18f00b03333a59f77d41dc1/lib/rpmdb.c#L2474

**Comment by newpavlov** [comment]
>What happens with --verifydb?

Weirdly enough, nothing.

>The problem might be that RPM wants the buildtime to be set. Could you try setting the build time, rebuilding and reinstalling the package?

IIUC the code snippet in the OP does set build time, no?

**Comment by dralley** [comment]
>IIUC the code snippet in the OP does set build time, no?

Derp, yes.  Ok.   Could you run `rpm --qp --xml $package_file` and `rpm -v --checksig $package_file` and paste the results?  Obviously using the actual filename.

**Comment by newpavlov** [comment]
It looks like you've been right and the issue was with lack of build time in the generated packets. When I was playing with the snippet I've commented out the `build_time` line and forgot to return it back.

I think it could be worth to enable inclusion of build time by default using current host time and keep the `build_time` method as a way to overwrite it for reproducible builds. Regardless whether it's an issue with `rpm` or documentation, the behavior is effectively a standard, so this crate arguably should accommodate for it.

**Comment by dralley** [comment]
Issue and discussion here https://github.com/rpm-software-management/rpm/issues/2527
