### ISSUE TITLE
Sort out ergonomics of reproducable builds

### ISSUE THREAD

**Issue by dralley** [rpm-rs/rpm#156]
re: https://github.com/rpm-rs/rpm/issues/117

Reproducable builds are possible now, if you provide both a `build_time` and a `source_date`.   But it would be best if users didn't need to know all the knobs.  In RPM, those knobs are:

* clamping file mtimes to a "source date epoch" value
* overriding the build time with the value of  "source date epoch"
* deriving "source date epoch" from the changelogs, which are static
* use a deterministic hostname

We avoid 4 by virtue of not setting the hostname by default.  We now have the ability to perform 1.  But we force the user to provide both `source_date` and a `build_time` manually and we don't provide a changelog shortcut, so it's not as simple as it could potentially be.

1) Is it OK to consolidate the options?
    * Is it OK to assume that the user is always ok with file mtime clamping behavior?
    * Is it OK to assume that `build_time` and `source_date` (the clamp value) ought to be the same in all cases? 
2) Should we provide some way to derive `source_date` from the changelogs automatically?

**Comment by dralley** [comment]
For what it's worth re: build_time `--rebuilddb` issues, they accepted as a bug and it has been fixed upstream.

**Comment by newpavlov** [comment]
I have implemented the clamping behavior for both modification and build times in #157.

>Should we provide some way to derive source_date from the changelogs automatically?

I think it should be handled by a higher-level software, not by this library. IIUC it's recommended to use timestamp of last commit in the project's VCS, which often is different from last changelog entry.

>re: build_time --rebuilddb issues, they accepted as a bug and it has been fixed upstream.

Good to know! Unfortunately, there is a lot of systems in the wild with outdated `rpm`, so we still have to include the build time tag to avoid potential problems.

**Comment by dralley** [comment]
I brought this up on Matrix with the person who contributed the ` %use_source_date_epoch_as_buildtime` option to RPM

> Him: I requested this flag be made because buildtime is used in some cases as a tie-break for packages of the same NEVRA in build systems and package managers. basically, it broke OBS and YUM if the buildtime was statically set

> Me: but the point of source_date_epoch is to make packages reproducable right?  If you allow the buildtime to be different, then the package is no longer reproducable, and there's no reason to use source_date_epoch. couldn't source_date_epoch just be disabled instead

> Him: I didn't want to say it outright in the commit, but it's quite common that build-time is used as a tie-breaker

> Him: then you don't get payload reproducibility, which is what actually matters. Debian style reproducibility is already pretty stupid to begin with, because you are foregoing specific package metadata that is useful for debugging purposes. However, because of the nature of RPMs, we can separate metadata and data reproducibility (Debian packages cannot do this)

> Me: so basically you still want the file mtime clamping, but don't care about the buildtime

> Him: yes. for Fedora, my recommendation is that buildhost and buildtime do not get clamped ever

So for the time being consolidating `build_time` and `source_date_epoch` might not be a good idea.  There seems to be a valid use case for having them be independent.

However:

> Me: I haven't checked too much on the details, but if RPMv6 new-style payloads exclusively use the header metadata (because otherwise metadata could be too large for CPIO), is that still going to serve any purpose?

> The payload at that point - I think - would be reproducible either way, because the payload wouldn't include any of that metadata?

> Him: yup

So when we start writing new-style payloads, that purpose will cease to exist.

**Comment by newpavlov** [comment]
In my project we specifically need full package reproducibility.  [Specification](https://reproducible-builds.org/specs/source-date-epoch/) of `SOURCE_DATE_EPOCH` explicitly states:

>Build processes MUST use this variable for embedded timestamps in place of the "current" date and time.

Also, as we have seen with the `--rebuilddb`, build time may not be even included into a package, so it's weird to rely on it in such way.

**Comment by newpavlov** [comment]
There is another open question: how we should handle timestamps included into signature? Right now current time is [used unconditionally](https://github.com/rpm-rs/rpm/blob/master/src/rpm/signature/pgp.rs#L38). Should we simply pass value of `source_date_epoch` to the sign method?

**Comment by dralley** [comment]
>Also, as we have seen with the `--rebuilddb`, build time may not be even included into a package, so it's weird to rely on it in such way.

It's understandable though.  If it was at all common, the `--rebuilddb` bug wouldn't have gone uncaught for literally 26 years (that bit of code is unchanged since 1997)

I feel kinda uncomfortable mucking around with the dates on signatures so in that sense I kind of see his point, too.  https://reproducible-builds.org/specs/source-date-epoch/ doesn't say anything about signatures.

**Comment by DemiMarie** [comment]
> @DemiMarie do you have thoughts.

Packages should be bitwise reproduceable.  That means that one should be able to take the digital signature from the official package, combine it with the package one has built oneself, and have the signature on the resulting package verify.

**Comment by dralley** [comment]
Ok.  In that case, yes, source_date needs to be passed over to the signing code when available and used for the signature.

**Comment by newpavlov** [comment]
>What is your project?

It's a cryptographic software which is in the process of passing certification. We distribute it in the form of DEB and RPM packages, hash sums of the packages will be included in the resulting certificate. As part of certification requirements build process must be completely offline and reproducible (as in we document resulting hashes and the certification body should be able to reproduce them). Of course, it's also about our clients being able to check the source code and to easily verify that we are not doing any funny business with the distributed packages.

**Comment by dralley** [comment]
Resolution: We did end up getting rid of a separate way to specify `build_time` even though it is useful, because in a couple of months we will be able to make changes that diminish its usefulness.
