### ISSUE TITLE
[Feature-Request] Adding `%pretrans` `%posttrans` scripts to builder

### ISSUE THREAD

**Issue by juliusl** [rpm-rs/rpm#199]
When rpm upgrades a package it will run all the install scripts of the new package before the uninstall scripts of the old package. 

The only hooks that are able to control overall pre/post steps seems to be %pretrans and %posttrans hooks of the new package.

Would it be possible to add these scripts to the Builder?

**Comment by dralley** [comment]
Of course, PR's accepted :)
