### ISSUE TITLE
Relicense as Apache 2.0 + MIT or some similarly permissive combination

### ISSUE THREAD

**Issue by dralley** [rpm-rs/rpm#27]
Currently this project is licensed as Apache 2.0, however Apache 2.0 licensing alone prevents use with GPL 2.0 licensed projects (this is contested, but at least the FSF seems to think they are incompatible licenses), which is why most projects in the Rust ecosystem nowadays use an Apache 2.0 + MIT dual-licensing scheme to improve compatibility.

To do this, realistically we would we need consent from all contributors. 

- [x] @Richterrettich 
- [x] @drahnr 
- [x] @dralley
- [x] @cmeister2
- [x] @indygreg 
- [x] @olivierlemasle
- [x] @TommyLike 
- [x] @Lunarequest 
- [x] @puiterwijk
- [x] @AlbertoBrusa
- [x] @volker-raschek

**Comment by Lunarequest** [comment]
I'm okay with this

**Comment by TommyLike** [comment]
I am ok

**Comment by puiterwijk** [comment]
I am okay with this relicensing.

**Comment by cmeister2** [comment]
Happy with relicensing

**Comment by AlbertoBrusa** [comment]
Happy with relicensing to Apache 2.0 + MIT dual-licensing or a similarly permissive license

**Comment by olivierlemasle** [comment]
Ok with the relicensing.

**Comment by Shinyzenith** [comment]
Sounds like a good plan!

**Comment by indygreg** [comment]
I consent to the relicensing.

**Comment by Lunarequest** [comment]
Does anyone know how to contact @Richterrettich?

**Comment by dralley** [comment]
Well, that's the whole reason this repo exists in the first place, he kind of stopped responding. 

We may be waiting a while.

**Comment by Lunarequest** [comment]
Would it be viable to rewrite his partitions

**Comment by dralley** [comment]
In theory, maybe, but it's probably not worth it.  He's the 2nd largest contributor and he'll probably turn back up eventually.

**Comment by Lunarequest** [comment]
We should start looking into it, from his history he's done one thing this year on github

**Comment by volker-raschek** [comment]
Richterrettich is a work colleague. I will contact him

**Comment by dralley** [comment]
If you are able to do that, that would be amazing - if he is willing to add @drahnr as an authorized publisher of the crate we could maintain continuity with the existing crate name rather than publishing it under a totally different name.

The only reason for the fork was because @Richterrettich was the only one who could push a new release.

**Comment by dralley** [comment]
@volker-raschek Were you able to get in touch?

**Comment by Richterrettich** [comment]
I am okay with this

**Comment by cmeister2** [comment]
Looks like we have everyone!

**Comment by TommyLike** [comment]
Cheers

**Comment by dralley** [comment]
@Richterrettich Hey!  Thanks for showing up :)

Would you be willing to add @drahnr and myself as co-owners / publishers of the `rpm-rs` crate so that development can continue?

**Comment by dralley** [comment]
@volker-raschek Could you forward my question?  Not sure he is getting the normal notifications

**Comment by drahnr** [comment]
I think the crate name mandates some more discussion https://github.com/rpm-rs/rpm/discussions/50
