### ISSUE TITLE
Support forum

### ISSUE THREAD

**Issue by Shinyzenith** [rpm-rs/rpm#3]
Should we create a matrix room for questions / general collaboration discussions?

**Comment by dralley** [comment]
I'm not against it but it feels a bit premature?  Or maybe not, maybe a bunch of people have questions :) 

gitter.im is a nice option though.

**Comment by drahnr** [comment]
There are already gh discussions, which I think should suffice for the time being: https://github.com/rpm-rs/rpm-rs/discussions

**Comment by ximon18** [comment]
> There are already gh discussions, which I think should suffice for the time being: https://github.com/rpm-rs/rpm-rs/discussions

I get a 404 Not Found error when I visit that link.

**Comment by drahnr** [comment]
https://github.com/rpm-rs/rpm/discussions
