### ISSUE TITLE
Get publishing permissions on rpm-rs, or rename this crate

### ISSUE THREAD

**Issue by cmeister2** [rpm-rs/rpm#4]
We need to get publishing permissions on the rpm-rs crate, or rename this to something else, otherwise further changes are moot.

**Comment by dralley** [comment]
No news.  The original contributor had some unrelated github activity 2 weeks ago but hasn't replied to emails or messages.

@cmeister2 I think, perhaps we should just continue publishing under the `fez` name for now.

**Comment by cmeister2** [comment]
Couldn't we just rename to something like `rpm2` in the meantime, so we can actually get on with adding features? I'd be happy to use `fez` too, but there's a bit of hassle there with the feature I added.

**Comment by dralley** [comment]
We could, I just figured if we already have a crate name, there's no need to create yet another one, that may eventually be abandoned anyway.

Is the feature not one that makes sense to upstream?

**Comment by dralley** [comment]
@Richterrettich Trying again to reach you : /

@cmeister2 Do you feel it's a hard blocker?

**Comment by olivierlemasle** [comment]
Hello @cmeister2 & @dralley,

Did you reach a decision regarding this crate? I'd be happy to contribute to this Richterrettich/rpm-rs fork, but I'd like to know if my pull requests are going to be merged some day, and if it a release of the forked crate will be made. If this fork is not more "maintained" that the original, that's a little bit sad...
Please understand that I feel entitled to nothing, that I do not blame you and that I really want to help :-)

@cmeister2 Regarding `fez`, **I'm not a lawyer**, but I'm not sure you had the right to change the license as you did. The StackExchange post you shared tells that you can use dependencies under one of them in a project under the other. It does not say you can re-license the work made by other authors. I do not think the part of 4 of the [Apache 2 license](https://apache.org/licenses/LICENSE-2.0.txt) enables you to change the license, even when you add a NOTICE file with the old license. This [other post from StackExchange](https://opensource.stackexchange.com/questions/9077/relicensing-from-apache-2-0-to-apache-or-mit) tells that you cannot re-license a project from Apache-2.0 to Apache-or-MIT without asking all the authors, so I guess it's the same thing (or worse!) to re-license from Apache-2.0 to MIT.

**Comment by cmeister2** [comment]
@olivierlemasle looks like you're right; I'll have to fix that. Might be easiest to just blat the code here into that repo and forgo the change I made for now, or archive it.

Regarding this fork; I'm not an admin here. It does seem like we're not getting anywhere with the original rpm-rs package though. If I had admin permissions here I'd probably rename this repo to `fez` and update everything to reflect that name, and then publish it to the `fez` crate.

**Comment by dralley** [comment]
Yeah, I emailed him again as well as the owner of the https://crates.io/crates/rpm crate which has gone unused, but not really expecting anything.

@drahnr Since you created the org I assume you have admin rights?  What are your thoughts on this.

IMO it would be OK to keep the repo named the way it is for now so long as we have it linked properly in Cargo.toml (which also shows up on crates.io)

**Comment by Shinyzenith** [comment]
Hello, I have been pretty invested with university lately so I apologize if I haven't carried out my duties properly. I'm still going through the thread and I'm slightly confused as to what we are trying to achieve, if anyone can summarize the issue that would be extremely helpful.

**Comment by drahnr** [comment]
@dralley I am happy to give you admin privileges.

I don't have a strong opinion, on naming, it'd be nice to continue with `rpm-rs` if possible, but my hopes are slim/low.

**Comment by dralley** [comment]
@drahnr I would appreciate that, thanks.

**Comment by dralley** [comment]
I have [one more idea](https://github.com/QubesOS/qubes-rpm-oxide/issues/12#issuecomment-1306094062)

**Comment by dralley** [comment]
@TommyLike Regarding the other thread, did you try to ping him?

**Comment by TommyLike** [comment]
> @TommyLike Regarding the other thread, did you manage to reach out on Slack?

No message replied on the slack till now, I am trying to reach him within other ways.

**Comment by drahnr** [comment]
> @drahnr I would appreciate that, thanks.

Done

**Comment by cmeister2** [comment]
In lieu of a solution I've published current `master` under `fez:0.8.1` (there were a couple of deprecations on the latest compiler that need looking into so I published manually).

**Comment by dralley** [comment]
@TommyLike I presume still no response from him?

That is disappointing but, so it goes.  The author of the `qubes-rpm-oxide` (not published on crates.io) said they would be be open to collaborating on one library under the name `rpm-oxide`, so, if we hear nothing back, that is what we should probably plan to do.

Or at least start that discussion.  https://github.com/QubesOS/qubes-rpm-oxide/issues/12#issuecomment-1306756814

**Comment by TommyLike** [comment]
@drahnr still need some time. hope I can contact him by this weekend.

**Comment by TommyLike** [comment]
@dralley hope it work now.

**Comment by dralley** [comment]
Indeed, we now have the `rpm` crate.

**Comment by drahnr** [comment]
I received the invite link, ty very much. I'll do an initial release after coordinating with rpm-rs

**Comment by drahnr** [comment]
Thank you!
