### ISSUE TITLE
Ensure compatibility with header-only package signing

### ISSUE THREAD

**Issue by dralley** [rpm-rs/rpm#97]
https://github.com/rpm-software-management/rpm/issues/863
https://github.com/rpm-software-management/rpm/issues/1107#issuecomment-1457971605

It seems like instead of storing an "main header + payload" signature, the modern approach is storing a payload digest in the main header, and taking a signature of the main header.

Let's make sure we're aligned with this.

**Comment by dralley** [comment]
Also relevant: https://github.com/rpm-software-management/rpm/issues/861

**Comment by saper** [comment]
Here is how I lost few hours of troubleshooting because of this:

I began to wonder why suddenly with enterprise linux 9 I am asked only once for signing PIN of my smartcard per file, it used to be twice for enterprise linux 8.

By coincidence, on enterprise linux 9 `rpmsign` additionally displays a useless warning when using a forwarded gpg agent connection:

    gpg: problem with fast path key listing: Forbidden - ignored

This turned out to be harmless (see https://github.com/gopasspw/gopass/issues/2485), but  I have started double-checking my signatures with ` rpm -q --qf '%{SIGPGP:pgpsig} %{SIGGPG:pgpsig}\n' -p XXXX` and started to wonder, why am I always getting `(none) (none)` for el9 as a result. 

**Could someone with a Red Hat account ask them to update https://access.redhat.com/articles/3359321 please?**

I've just spent quite some time trying to figure out why on el8 with rpm-4.14.3-24.el8_7.x86_64 I am getting this:

```
$ rpm -q --qf '%{SIGPGP:pgpsig}\n' -p uboot-tools-2023.04-0.3.rc4.el8.src.rpm 
RSA/SHA256, Mon 20 Mar 2023 04:46:11 PM EDT, Key ID 128259108b318951
```

but on el9 with rpm-4.16.1.3-19.el9_1.x86_64

```
$ rpm -q --qf '%{SIGPGP:pgpsig}\n' uboot-tools-2023.04-0.3.rc4.el9.src.rpm 
(none)
```

One should recommend using also 

```
$ rpm -q --qf '%{RSAHEADER:pgpsig}\n' uboot-tools-2023.04-0.3.rc4.el9.src.rpm 
RSA/SHA256, Mon Mar 20 22:16:37 2023, Key ID 128259108b318951
```

and for checking signatures `-v` should be used to explain what happened:

el8:

```
$ rpm --checksig -v uboot-tools-2023.04-0.3.rc4.el8.src.rpm 
uboot-tools-2023.04-0.3.rc4.el8.src.rpm:
    Header V4 RSA/SHA256 Signature, key ID 8b318951: OK
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    V4 RSA/SHA256 Signature, key ID 8b318951: OK
    MD5 digest: OK
```

el9:

```
$ rpm --checksig -v uboot-tools-2023.04-0.3.rc4.el9.src.rpm 
uboot-tools-2023.04-0.3.rc4.el9.src.rpm:
    Header V4 RSA/SHA256 Signature, key ID 8b318951: OK
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    MD5 digest: OK
```

All tests were done using AlmaLinux 8 and 9 respectively.

**Comment by dralley** [comment]
So keep in mind that with respect to `rpm` and `rpmsign`, the correct repo is https://github.com/rpm-software-management/rpm

With that said, 

>Could someone with a Red Hat account ask them to update https://access.redhat.com/articles/3359321 please?

Yes I will bring that up.

**Comment by saper** [comment]
Sorry, came here from https://github.com/rpm-software-management/rpm/issues/861. Thank you!

**Comment by dralley** [comment]
@saper Did you determine which version stopped automatically setting that particular header entry?

**Comment by saper** [comment]
I haven't experimented with this, but [4.16.0 release notes](http://rpm.org/wiki/Releases/4.16.0) say

> Signatures and keys
>    Add verify support for alternative signatures and digests
>    Fix package signing regression on some non-rpm.org built packages (#1002)
>    Drop RPM v3 header+payload signatures by default, where possible (#863)

which lead me to https://github.com/rpm-software-management/rpm/issues/863 and here.

**Comment by dralley** [comment]
I'll add as an extension to this - "support Ed25519 / EdDSA signatures" and not just RSA.

**Comment by dralley** [comment]
@saper I edited the post FYI

**Comment by TommyLike** [comment]
@dralley How can we generate v4 signature with RSA pgp key now? It looks like we have to specify the header and header+payload signature currently.
```
 pub fn add_rsa_signature(
        mut self,
        sig_header_only: &[u8],
        sig_header_and_archive: &[u8],
    ) -> SignatureHeaderBuilder<WithSignature> {
        let offset = 0i32; // filled externally later on
        self.entries.push(IndexEntry::new(
            IndexSignatureTag::RPMSIGTAG_RSA,
            offset,
            IndexData::Bin(sig_header_only.to_vec()),
        ));
        self.entries.push(IndexEntry::new(
            IndexSignatureTag::RPMSIGTAG_PGP,
            offset,
            IndexData::Bin(sig_header_and_archive.to_vec()),
        ));
        SignatureHeaderBuilder::<WithSignature> {
            entries: self.entries,
            phantom: Default::default(),
        }
    }
```

**Comment by dralley** [comment]
@TommyLike You're referring to generating a signature separately from the package itself, yeah?

To be honest this API, despite being public, is basically internal-only by virtue of being not convenient at all to use.

**Comment by TommyLike** [comment]
@dralley Thanks, I mean the same behaviour in rpm-rs with rpmsign command https://man7.org/linux/man-pages/man8/rpmsign.8.html.
```
       --rpmv3
              Force RPM V3 header+payload signature addition.  These are
              expensive and redundant baggage on packages where a
              separate payload digest exists (packages built with rpm >=
              4.14).  Rpm will automatically detect the need for V3
              signatures, but this option can be used to force their
              creation if the packages must be fully signature
              verifiable with rpm < 4.14 or other interoperability
              reasons.
```

**Comment by TommyLike** [comment]
We have to sign header and header+payload currently which means much more calcualtion and network transfer (for our use cases) especially for large rpm, if we can support v4 signature, it would be great helpful

**Comment by dralley** [comment]
@TommyLike Currently both RPMv3 and header-only signatures are always produced, there's no way to avoid one or the other.  My thinking was that in a couple of months RHEL 7 will be close enough to EOL that we can just ditch RPMv3 signature support entirely and not worry too much about complicating the APIs.

**Comment by dralley** [comment]
If you are open to submitting a PR that puts all the legacy signatures and digests behind a default feature (that could then be turned off for your use), I would be willing to merge it.

**Comment by TommyLike** [comment]
> @TommyLike Currently both RPMv3 and header-only signatures are always produced, there's no way to avoid one or the other. My thinking was that in a couple of months RHEL 7 will be close enough to EOL that we can just ditch RPMv3 signature support entirely and not worry too much about complicating the APIs.
> 
> If you need the ability to do so now, then we could consider putting that behind a feature.

Thanks, we need this support, btw, why dsa signature is missing the payload stuff? @dralley 
```
pub fn add_eddsa_signature(
        mut self,
        sig_header_only: &[u8],
    ) -> SignatureHeaderBuilder<WithSignature> {
        let offset = 0i32; // filled externally later on
        self.entries.push(IndexEntry::new(
            IndexSignatureTag::RPMSIGTAG_DSA,
            offset,
            IndexData::Bin(sig_header_only.to_vec()),
        ));
        SignatureHeaderBuilder::<WithSignature> {
            entries: self.entries,
            phantom: Default::default(),
        }
    }
```

**Comment by dralley** [comment]
>btw, why dsa signature is missing the payload stuff? @dralley

Because "DSA" was reused for "EdDSA" signatures (personally I think that was not the best decision, but that's what was done).  And, any version of RPM that is capable of producing EdDSA signed packages, doesn't need all the legacy stuff to be there.  Or conversely there is no version of RPM which only understands the legacy stuff, which would be able to understand an EdDSA signature being used.  So using it there would be pointless.

**Comment by TommyLike** [comment]
> If you are open to submitting a PR that puts all the legacy signatures and digests behind a default feature (that could then be turned off for your use), I would be willing to merge it.

I am not sure if I can work it out correctly. 😄

**Comment by dralley** [comment]
I have a commit lying around that removes v3 signatures (waiting for when I can finally merge it in a few months)

```diff
commit 8d3247055abcc8a6836e965a01cdaee884a943ed
Author: Daniel Alley <dalley@redhat.com>
Date:   Mon Apr 17 18:21:09 2023 -0400

    Remove v3 PGP signature from builder

diff --git a/src/rpm/builder.rs b/src/rpm/builder.rs
index 79acb84..6003198 100644
--- a/src/rpm/builder.rs
+++ b/src/rpm/builder.rs
@@ -2,8 +2,6 @@ use std::collections::{BTreeMap, BTreeSet};
 use std::convert::TryInto;
 
 use std::fs;
-#[cfg(feature = "signature-meta")]
-use std::io;
 use std::io::{Read, Write};
 #[cfg(unix)]
 use std::os::unix::fs::PermissionsExt;
@@ -541,13 +539,9 @@ impl RPMBuilder {
         let signature_header = {
             let rsa_sig_header_only = signer.sign(header.as_slice())?;
 
-            let cursor = io::Cursor::new(header).chain(io::Cursor::new(&content));
-            let rsa_sig_header_and_archive = signer.sign(cursor)?;
-
             builder
                 .add_signature(
                     rsa_sig_header_only.as_ref(),
-                    rsa_sig_header_and_archive.as_ref(),
                 )
                 .build(header_and_content_len)
         };
diff --git a/src/rpm/headers/header.rs b/src/rpm/headers/header.rs
index 2dbad25..6005573 100644
--- a/src/rpm/headers/header.rs
+++ b/src/rpm/headers/header.rs
@@ -335,11 +335,10 @@ impl Header<IndexSignatureTag> {
         sha1: &str,
         sha256: &str,
         rsa_spanning_header: &[u8],
-        rsa_spanning_header_and_archive: &[u8],
     ) -> Self {
         SignatureHeaderBuilder::new()
             .add_digest(sha1, sha256, md5sum)
-            .add_signature(rsa_spanning_header, rsa_spanning_header_and_archive)
+            .add_signature(rsa_spanning_header)
             .build(headers_plus_payload_size)
     }
 
@@ -917,7 +916,6 @@ mod test {
         let sha1 = "5A884F0CB41EC3DA6D6E7FC2F6AB9DECA8826E8D";
         let sha256 = "E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855";
         let rsa_spanning_header: &[u8] = b"111222333444";
-        let rsa_spanning_header_and_archive: &[u8] = b"7777888899990000";
 
         let truth = {
             let offset = 0;
@@ -948,11 +946,6 @@ mod test {
                     offset,
                     IndexData::Bin(rsa_spanning_header.to_vec()),
                 ),
-                IndexEntry::new(
-                    IndexSignatureTag::RPMSIGTAG_PGP,
-                    offset,
-                    IndexData::Bin(rsa_spanning_header_and_archive.to_vec()),
-                ),
             ];
             Header::<IndexSignatureTag>::from_entries(entries, IndexSignatureTag::HEADER_SIGNATURES)
         };
@@ -963,7 +956,6 @@ mod test {
             sha1,
             sha256,
             rsa_spanning_header,
-            rsa_spanning_header_and_archive,
         );
 
         assert_eq!(built, truth);
diff --git a/src/rpm/headers/signature_builder.rs b/src/rpm/headers/signature_builder.rs
index b69edeb..7e8d996 100644
--- a/src/rpm/headers/signature_builder.rs
+++ b/src/rpm/headers/signature_builder.rs
@@ -114,7 +114,6 @@ impl SignatureHeaderBuilder<WithDigest> {
     pub fn add_signature(
         mut self,
         rsa_sig_header_only: &[u8],
-        rsa_sig_header_and_archive: &[u8],
     ) -> SignatureHeaderBuilder<WithSignature> {
         let offset = 0i32; // filled externally later on
         self.entries.push(IndexEntry::new(
@@ -122,11 +121,6 @@ impl SignatureHeaderBuilder<WithDigest> {
             offset,
             IndexData::Bin(rsa_sig_header_only.to_vec()),
         ));
-        self.entries.push(IndexEntry::new(
-            IndexSignatureTag::RPMSIGTAG_PGP,
-            offset,
-            IndexData::Bin(rsa_sig_header_and_archive.to_vec()),
-        ));
         SignatureHeaderBuilder::<WithSignature> {
             entries: self.entries,
             phantom: Default::default(),
@@ -142,7 +136,6 @@ mod test {
         let builder = SignatureHeaderBuilder::<Empty>::new();
 
         let rsa_sig_header_only = [0u8; 32];
-        let rsa_sig_header_and_archive = [0u8; 32];
 
         let digest_header_sha1 = hex::encode([0u8; 64]);
         let digest_header_sha256: String = hex::encode([0u8; 64]);
@@ -155,15 +148,12 @@ mod test {
                 digest_header_sha256.as_str(),
                 &digest_header_and_archive[..],
             )
-            .add_signature(&rsa_sig_header_only[..], &rsa_sig_header_and_archive[..])
+            .add_signature(&rsa_sig_header_only[..])
             .build(32);
 
         assert!(header
             .find_entry_or_err(IndexSignatureTag::RPMSIGTAG_RSA)
             .is_ok());
-        assert!(header
-            .find_entry_or_err(IndexSignatureTag::RPMSIGTAG_PGP)
-            .is_ok());
         assert!(header
             .find_entry_or_err(IndexSignatureTag::RPMSIGTAG_MD5)
             .is_ok());
@@ -195,9 +185,6 @@ mod test {
         assert!(header
             .find_entry_or_err(IndexSignatureTag::RPMSIGTAG_RSA)
             .is_err());
-        assert!(header
-            .find_entry_or_err(IndexSignatureTag::RPMSIGTAG_PGP)
-            .is_err());
         assert!(header
             .find_entry_or_err(IndexSignatureTag::RPMSIGTAG_MD5)
             .is_ok());
diff --git a/src/rpm/package.rs b/src/rpm/package.rs
index 71626ec..9755f8a 100644
--- a/src/rpm/package.rs
+++ b/src/rpm/package.rs
@@ -121,12 +121,6 @@ impl RPMPackage {
         } = Self::create_sig_header_digests(header_bytes.as_slice(), &self.content)?;
 
         let rsa_signature_spanning_header_only = signer.sign(header_bytes.as_slice())?;
-        let mut header_and_content_cursor =
-            io::Cursor::new(header_bytes).chain(io::Cursor::new(&self.content));
-
-        let rsa_signature_spanning_header_and_archive =
-            signer.sign(&mut header_and_content_cursor)?;
-
         // NOTE: size stands for the combined size of header and payload.
         self.metadata.signature = Header::<IndexSignatureTag>::new_signature_header(
             header_and_content_len,
@@ -134,7 +128,6 @@ impl RPMPackage {
             &header_digest_sha1,
             &header_digest_sha256,
             rsa_signature_spanning_header_only.as_slice(),
-            rsa_signature_spanning_header_and_archive.as_slice(),
         );
 
         Ok(())

```

**Comment by dralley** [comment]
I guess alternatively you could just change the name of `add_rsa_signature` to `add_rsa_signature_with_legacy` and then define your own `add_rsa_signature` which skips that part.  That would probably be OK too.

**Comment by TommyLike** [comment]
> I guess alternatively you could just change the name of `add_rsa_signature` to `add_rsa_signature_with_legacy_v3` and then define your own `add_rsa_signature` which skips that part. That would probably be OK too.
> 
> So long as the standard APIs most people use (`Package::sign`) continue generating the legacy signatures, for now.

If it would be as easy as remove the "RPMSIGTAG_PGP" tag itself, I can remove this part in my forked version, and upgrade it to upstream version once it has been support in rpm-rs. Thanks @dralley
